config/routes.rb
Rails.application.routes.draw do
  root 'youtubers#index'
  devise_for :users
devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "/mypage" => "users#mypage"
  get "/users/edit" => "users#edit"
  patch "/users" => "users#update"
end
 #get 'tags/index'
  resources :tags, only: [:index, :create]
  resources :styles
  get "/about" => "homes#about"
  resources :users
  resources :youtubers do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :youtuber
 # validates :rate, numericality: {
 #  less_than_or_equal_to: 5,
 #   greater_than_or_equal_to: 1}, presence: true
end

app/models/style.rb
class Style < ApplicationRecord
  acts_as_taggable
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image


  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得できる。
end

app/models/youtuber.rb
class Youtuber < ApplicationRecord
  has_many :youtuber_tags,dependent: :destroy
  has_many :comments, dependent: :destroy  #Post.commentsで、投稿が所有するコメントw取得できる。
  attachment :image
  acts_as_taggable_on :tags

  # Tag Save & Remove
  def tag_diff(tags)
    # Tag Split
    current_tags = tag_list.split(',')
    save_tags = tags.split(',')

    old_tags = (current_tags - save_tags).join(',') # Old Tags
    new_tags = (save_tags - current_tags).join(',') # New Tags

    # Remove '#'
    old_tags.delete!('#')
    new_tags.delete!('#')

    # Tag Save & Remove
    tag_list.remove(old_tags, parse: true)
    tag_list.add(new_tags, parse: true)
  end
end

app/models/youtuber_tag.rb
class YoutuberTag < ApplicationRecord
  belongs_to :youtuber
  #belongs_to :tag
  validates :youtuber_id, presence: true
  # validates :tag_id, presence: true
end

app/models/youtubert_tag.rb
class YoutubertTag < ApplicationRecord
  belongs_to :youtuber
  belongs_to :tag
  validates :youtuber_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save!
      redirect_back(fallback_location: root_path)  #コメント送信後は、一つ前のページへリダイレクトさせる。
    else
      redirect_back(fallback_location: root_path)  #同上
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content, :youtuber_id, :rate,)  #formにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
    # タグの一覧表示
    if params[:tag]
      @styles = Style.tagged_with(params[:tag])
      # タグ検索時にそのタグずけしているものを表示
    else
      @styles = Style.all
    end
  end
  def new
    @style = Style.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @style = Youtuber.tagged_with(params[:id])
  end

  def create
    @style = Style.new(style_params)
    @style.user_id = current_user.id
    if @style.save
      flash[:notice] = "スタイルを登録しました"
      redirect_to style_path(@style.id)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :new
    end
  end
# update・destroyは同じような形なので省略します
  private

    def style_params
      params.require(:style).permit(:name, :user_id, :image, tag_list: [])
      #  tag_list: []　を追記
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to action: :index
    else
      render template: "tags/index"
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def mypage
    @user = current_user
    render template: "users/show"
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/youtubers_controller.rb
class YoutubersController < ApplicationController
  before_action :set_youtuber, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new]

  # GET /youtubers or /youtubers.json
  def index
    
    @youtubers = Youtuber.all.page(params[:page]).per(10)

  end

  # GET /youtubers/1 or /youtubers/1.json
  def show
    @youtuber = Youtuber.find(params[:id])
    #@youtuber_tags = @youtuber.tags
    @comments = @youtuber.comments  #投稿詳細に関連付けてあるコメントを全取得
    if user_signed_in?
      @comment = current_user.comments.new  #投稿詳細画面でコメントの投稿を行うので、formのパラメータ用にCommentオブジェクトを取得
    end
  end

  # GET /youtubers/new
  def new
    flash[:notice] = "ログイン済ユーザーのみ新規Youtuberを追加できます" unless user_signed_in?
    @youtuber = Youtuber.new
  end

  # GET /youtubers/1/edit
  def edit
  end

  # POST /youtubers or /youtubers.json
  def create
    @youtuber = Youtuber.new(youtuber_params)
    @youtuber.user_id=current_user.id
    # 受け取った値を,で区切って配列にする
    # tag_list=params[:youtuber][:name].split(',')
    @youtuber.tag_diff(params[:youtuber][:tag])
    if @youtuber.save
      # @youtuber.save_tag(tag_list)
      redirect_to youtubers_path, notice:'投稿完了しました:)'
    else
      render:new
    end
  end

  # PATCH/PUT /youtubers/1 or /youtubers/1.json
  def update
    respond_to do |format|
      if @youtuber.update(youtuber_params)
        format.html { redirect_to @youtuber, notice: "Youtuber was successfully updated." }
        format.json { render :show, status: :ok, location: @youtuber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @youtuber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /youtubers/1 or /youtubers/1.json
  def destroy
    @youtuber.destroy
    respond_to do |format|
      format.html { redirect_to youtubers_url, notice: "Youtuber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    # キーワード検索
    @search = Youtuber.ransack(params[:q])
    @results = @search.result.order("created_at DESC").page(params[:page]).per(10)
    # タグ検索
    @tag_search = Youtuber.tagged_with(params[:search])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_youtuber
      @youtuber = Youtuber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def youtuber_params
      params.require(:youtuber).permit(:name, :image, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/youtuber_helper.rb
module YoutuberHelper
end

app/helpers/youtubers_helper.rb
module YoutubersHelper
end

app/views/comments/new.html.erb
<%= form_with(model: [product, product_comment], url: product_product_comments_path(product), local: true) do |f| %>
    <%= render 'layouts/error_messages', object: f.object %>

    <%= f.text_area :comment, rows:'5', placeholder: "商品のコメント", class: "form-control form-control-sm" %>
    <div id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <%= f.hidden_field :rate, :value => 'score' %>
    </div>

    <%= f.submit "投稿する" %>
<% end %>


<script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        scoreName: 'product_comment[rate]'
    });
</script>

app/views/comments/show.html.erb
<% youtuber.youtuber_comments.each do |youtuber_comment| %>
    <div class="pt-2 px-2" style="background-color: #fffffe; border: 2px solid #272343; border-radius: 2px;">
        <%# rateを表示 %>
        <div class="review-rating" data-score="<%= product_comment.rate %>">評価：</div>
        
        <div class="text-left">
            <p>投稿者：<%= youtuber_comment.user.name %></p>
            <p><%= youtuber_comment.comment %></p>
        </div>

        <div class="text-right">
            <p>
                投稿日：<%= youtuber_comment.created_at.strftime('%Y/%m/%d') %> |
                <% if youtuber_comment.user == current_user %>
                    <%= link_to youtuber_youtuber_comment_path(youtuber_comment.youtuber, youtuber_comment), method: :delete, class: "btn btn-sm btn-danger" do %>
                        コメント削除 <i class="fas fa-trash"></i>
                    <% end %>
                <% end %>
            </p>
        </div>
    </div>

    <div class="pb-2"></div>

<% end %>

app/views/styles/index.html.erb
<div class="col-xs-12">
   
   <%= link_to "＋", new_style_path, class: "btn btn-success rounded-circle p-2" %>
   <% @tags.each do |tag| %>
      <%= link_to "#{tag.name}(#{tag.taggings_count})", style_path(tag.name), class: "label label-default" %>
   <% end %>
</div>

app/views/styles/new.html.erb
<%= form_for @style do |f| %>
  <div class="col-xs-12">
    <label class="col-sm-12">タグ</label>
      <div class="col-sm-12">
        <% @tags.each do |tag| %>
          いらない<%= f.check_box :tag_list, { multiple: true }, "#{tag.name}", nil %>
          <%= f.label " #{tag.name}(#{tag.taggings_count})", class: "label label-default" %>
        <% end %>
      </div>

      <div class="col-sm-12 text-right">
        <%= f.submit "新規作成", class: "btn btn-danger" %>
      </div>
   </div>
  </div>
<% end %>

app/views/styles/show.html.erb
<label class="col-sm-12 my-top">
   <%#= raw(@style.tag_list.map { |t| link_to t, tag_path(t), class: "label label-default" }.join(' ')) %>
</label>

<% @style.each do |tag| %>
  <%= link_to tag.name, youtuber_path(tag) %>
<% end %>

app/views/tags/index.html.erb
<div class="container">
  <h1 class="title">タグ一覧</h1>
  <div class="rowr">
    <div class="tags">
      <% if @tags.present? %>
         <% @tags.each do |tag| %>
          <%= link_to "#{tag.name}(#{tag.taggings_count})",search_youtubers_path(search: tag.name), class: "label label-default" %>
       <% end %>
      <% end %>
    </div>
  </div>
  <% if @tag.errors.present? %>
    <% @tag.errors.full_messages.each do |full_message| %>
    <%= full_message %>
    <% end %>
  <% end %>
  <div class="row">

  </div>
  <%= form_with model: @tag, url: tags_path, local: true do |f| %>
  <div class="row">
    <div class="col-lg-7, mx-auto">
      <table>
        <tr>
          <th>タグ名</th>
          <th><%= f.text_field :name %></th>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2, mx-auto">
       <%= f.submit "新規タグ作成", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
<%= form_with model:@user, local:true do |f| %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
        </div>

        <div class="form-group">
          <label for="user-image">image</label><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div>

        <div class="form-group">
          <label for="user_introduction">introduction</label>
          <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
    </div>
  </div>
</div>

<% end %>

app/views/users/show.html.erb
<h2 class="title">User info</h2>

<div class="container">
  <div class="row">
    <div class="col-6">
      <table class="table">
        <tbody>
          <tr><td>
            <%= attachment_image_tag @user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
          </td></tr>

          <tr>
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>

          <tr>
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>

          <tr><% if @user.id == current_user.id %>
            <td colspan="2"><%= link_to "編集", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></td>
          <% end %></tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/youtubers/_form.html.erb
<%= form_with(model: youtuber, local: true) do |form| %>
  <% if youtuber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(youtuber.errors.count, "error") %> prohibited this youtuber from being saved:</h2>

      <ul>
      <% youtuber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image_id %>
    <%= form.text_field :image_id %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/youtubers/_tag.html.erb
<li><%= link_to a_product.name, "/youtubers/#{a_product.id}" %>
<p><%= attachment_image_tag a_product, :image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %></p></li>

app/views/youtubers/_youtuber.html.erb
<li><%= link_to a_product.name, "/youtubers/#{a_product.id}" %>
<p><%= attachment_image_tag a_product, :image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %></p></li>

app/views/youtubers/edit.html.erb
<h1>Editing Youtuber</h1>

<%= render 'form', youtuber: @youtuber %>

<%= link_to 'Show', @youtuber %> |
<%= link_to 'Back', youtubers_path %>

app/views/youtubers/index.html.erb
<h1 class="title">Youtuber一覧</h1>
<div class="container">
  <div class="row">
    <div class="col">
      <%= link_to "＋", new_youtuber_path, class: "btn btn-success rounded-circle p-2" %>
    </div>
  <div class="row">
    <% @youtubers.each do |youtuber| %>
      <span claa="name"><%= link_to youtuber.name, "/youtubers/#{youtuber.id}" %></span>
      <p><%= attachment_image_tag youtuber, :image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %></p>
      <div id="star-rate-average-<%= youtuber.id %>"></div>
    <% end %>
  </div>
</div>
<div class="page">
  <%= paginate @youtubers %>
</div>
<script>
      <% @youtubers.each do |youtuber| %>
        $("#star-rate-average-<%= youtuber.id %>").empty();
        $("#star-rate-average-<%= youtuber.id %>").raty({
          size: 36,
          starOff: "<%= asset_path('star-off.png') %>",
          starOn: "<%= asset_path('star-on.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          half: true,
          readOnly: true,
          score: "<%= youtuber.comments.average(:rate).to_f.round(1) %>",
        //注目ポイント↑ 平均点を算出し、round関数で切り上げ
        });
      <% end %>
</script>

app/views/youtubers/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="title">Youtuber新規登録</h2>
  </div>
  <%= form_with model: @youtuber, url: youtubers_path, local:true do |f| %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table>
        <tr>
          <th>Youtuber画像</th>
          <th><%= f.attachment_field :image, placeholder:"Youtuber画像" %></th>
        </tr>
        <tr>
          <th>Youtuber名</th>
          <th><%= f.text_field :name %></th>
        </tr>
        <tr>
          <th>Youtuber説明</th>
          <th><%= f.text_area :introduction %></th>
        </tr>
        <tr>
          <th>タグ(,で区切れます)</th>
          <th><%= f.text_field :tag %></th>
        </tr>
        <tr>
          <th>URL</th>
          <th><%= f.text_field :url %></th>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2, mx-auto">
       <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/youtubers/search.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">

      <!--キーワード検索-->
      <div id ="test1" >
 　　　　　　　　　　　<!--Ransackを使うとsearch_form_forを使える！-->
        <%= search_form_for @search,url: search_youtubers_path do |f| %>

          <div class="form-group">
            <i class="material-icons prefix">キーワード検索</i>
            <%= f.search_field :name_cont, class: 'form-control', placeholder: 'キーワードで検索' %>
            <%= f.submit '検索',:class => "btn btn-success" %>
          </div>
        <% end %>
      <!--キーワード検索の結果を表示-->
        <div class="col s6">
          <div class="card" id = "test1">
            <div class="blue-grey darken-1">
              <ul class="card mb-0">
                <% @results.each do |result| %>
                  <%= render 'youtubers/youtuber' , a_product: result %>
                  <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!--タグ検索-->
      <div id ="test2">
        <div class="form-group">
        <i class="material-icons prefix">タグ検索</i>
        <!--タグはform_tagを用いて-->
        <%= form_tag('search', method: "get") do %>
          <%= text_field_tag :search %>
          <%= submit_tag '検索', :class =>  "btn btn-success" %>
        <% end %>
        </div>
　　　　　　　　　　　　　　　<!--タグ検索の結果を表示-->
        <div class="col s6">
          <div class="card" id = "test1">
            <div class="blue-grey darken-1">
              <ul class="card mb-0">
                <% @tag_search.each do |result| %>
                  <%= render 'tag' , a_product: result %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/youtubers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 col-offset-3">
      <h2 class="title">Youtuber詳細</h2>
    </div>
  </div>
  <div class="col-6 col-offset-4">
    <h4>Youtuberの名前</h4>
    <p><%= @youtuber.name %></p>
    <h4>説明</h4>
    <p><%= @youtuber.introduction %></p>
    <h4>画像</h4>
    <%= attachment_image_tag @youtuber, :image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
    <h4>評価</h4>
    <div id="star-rate-average-<%= @youtuber.id %>"></div>
    <h4>タグ</h4>
    <div class="tag"><% @youtuber.tag_list.each do |tag| %>
      <%= tag %>&nbsp;&nbsp;
    <% end %></div>
    <h4>URL</h4>
    <p><%= @youtuber.url %></p>
    <a class="btn btn-primary text-white" href="#" role="button">Youtuberのチャンネルへ</a>

  </div>
  <script>
      $("#star-rate-average-<%= @youtuber.id %>").raty({
        size: 36,
        starOff: "<%= asset_path('star-off.png') %>",
        starOn: "<%= asset_path('star-on.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        half: true,
        readOnly: true,
        score: "<%= @youtuber.comments.average(:rate).to_f.round(1) %>",
        //ポイント↑ 平均点を算出し、round関数で切り上げ
      });
    </script>

<% if user_signed_in? %>
  <h4>コメントをする</h4>
  <%= form_with(model:[@youtuber, @comment], method: :youtuber) do |f| %>
<!--商品コードの送信-->
    <%= f.hidden_field :youtuber_id, { value: @youtuber.id} %>

<!-- 評価 -->
    <div class="form-group row" id="star">
      <%= f.label :rate,'評価 ', class:'col-md-3 col-form-label' %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>


  <!-- 口コミ -->
    <div class="form-group row">
      <%= f.label :content, 'コメント ', class:'col-md-3 col-form-label' %>
      <div class="col-md-9">
      <%= f.text_area :comment_content, class: "form-control", rows: "8",
        placeholder:'ここにコメントを入力してください' %>
      </div>
    </div>

  <!-- 確認ボタン -->
    <div class="form-group row justify-content-end">
      <div class="col-md-9">
        <%= f.submit '投稿する', class:"btn btn-success" %>
      </div>
    </div>

  <% end %>


  <!-- 評価javascript -->
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'comment[rate]',
    half: true,
  });
  </script>
<% end %>

<h4>コメント一覧</h4>
<% if @comments.present? %>
  <% @comments.each do |comment| %>
    <div class="row posts">
      <div class="col-md-2 comments-user">
        <%= link_to user_path(comment.user) do %>
          <%= comment.user.name %>
          <%= attachment_image_tag comment.user, :profile_image, size: '100x100', format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
        <p class="comments-title"><%#= link_to comment.user.name, comment.user %></p>
        <p class="comments-prof"><%#= comment.user.gender %> <%#= comment.user.height %> <%#= comment.user.weight %></p>
      </div>
      <div class="col-md-6 mb-3">
        <div class=" comments-content">
          <p><%#= simple_time(comment.created_at) %></p>
          <h4 class="mb-3">評価：<%= comment.rate %>点 | <%#= comment.title %></h4>

          <!--星評価-->
         <div id="star-rate-<%= comment.id %>"></div>
          <script>
          $('#star-rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= comment.rate %>,
          });
          </script>
        <!--/星評価-->

          <p><%= comment.comment_content %></p>
          <%#= image_tag comment.picture.url, class:'img-fluid' if comment.picture? %>
        </div>
      </div>
      <div class="col-md-4">
        <%#= link_to comment.product do %>
          <div class="comments-product">
            <img src="<%#= comment.product.image_url %>" alt="">
            <p><%#=  comment.product.title %></p>
          </div>
        <%# end %>
      </div>
      <div class="col-md-12 edit-button">
        <%# if current_user == comment.user %>
          <%#= link_to '口コミを編集', edit_post_path(post), method: :get, class:'btn btn-default' %>
          <%#= link_to '口コミを削除', post, method: :delete, class:'btn btn-default' %>
        <%# end %>
      </div>
    </div>
  <% end %>
<% end %>