config/routes.rb
Rails.application.routes.draw do
  root 'youtubers#index'
  devise_for :users
devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "/mypage" => "users#mypage"
  get "/users/edit" => "users#edit"
  patch "/users" => "users#update"
end
 #get 'tags/index'
  resources :tags, only: [:index, :create]
  resources :styles
  get "/about" => "homes#about"
  resources :users
  resources :youtubers do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :youtuber
 # validates :rate, numericality: {
 #  less_than_or_equal_to: 5,
 #   greater_than_or_equal_to: 1}, presence: true
end

app/models/style.rb
class Style < ApplicationRecord
  acts_as_taggable
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image


  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得できる。
end

app/models/youtuber.rb
class Youtuber < ApplicationRecord
  has_many :youtuber_tags,dependent: :destroy
  has_many :comments, dependent: :destroy  #Post.commentsで、投稿が所有するコメントw取得できる。
  attachment :image
  acts_as_taggable_on :tags

  # Tag Save & Remove
  def tag_diff(tags)
    # Tag Split
    current_tags = tag_list.split(',')
    save_tags = tags.split(',')

    old_tags = (current_tags - save_tags).join(',') # Old Tags
    new_tags = (save_tags - current_tags).join(',') # New Tags

    # Remove '#'
    old_tags.delete!('#')
    new_tags.delete!('#')

    # Tag Save & Remove
    tag_list.remove(old_tags, parse: true)
    tag_list.add(new_tags, parse: true)
  end
end

app/models/youtuber_tag.rb
class YoutuberTag < ApplicationRecord
  belongs_to :youtuber
  #belongs_to :tag
  validates :youtuber_id, presence: true
  # validates :tag_id, presence: true
end

app/models/youtubert_tag.rb
class YoutubertTag < ApplicationRecord
  belongs_to :youtuber
  belongs_to :tag
  validates :youtuber_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
    # タグの一覧表示
    if params[:tag]
      @styles = Style.tagged_with(params[:tag])
      # タグ検索時にそのタグずけしているものを表示
    else
      @styles = Style.all
    end
  end
  def new
    @style = Style.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @style = Youtuber.tagged_with(params[:id])
  end

  def create
    @style = Style.new(style_params)
    @style.user_id = current_user.id
    if @style.save
      flash[:notice] = "スタイルを登録しました"
      redirect_to style_path(@style.id)
    else
      @tags = ActsAsTaggableOn::Tag.all
      render :new
    end
  end
# update・destroyは同じような形なので省略します
  private

    def style_params
      params.require(:style).permit(:name, :user_id, :image, tag_list: [])
      #  tag_list: []　を追記
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to action: :index
    else
      render template: "tags/index"
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def mypage
    @user = current_user
    render template: "users/show"
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/youtuber_helper.rb
module YoutuberHelper
end

app/helpers/youtubers_helper.rb
module YoutubersHelper
end

app/views/layouts/_footer.html.erb
<div class="d-flex align-items-center justify-content-center" style="height:100px">
  For Youtuber
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "ForYoutubers", root_path, class:"btn btn-light btn-outline-secondary btn-margin" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-md-auto align-items-center" >
        <% if user_signed_in? %>
          <li>ようこそ、<%= current_user.name %>さん！</li>
          <li><%= link_to "About", about_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "マイページ", mypage_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "Youtuber一覧", youtubers_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "新規Youtuber投稿", new_youtuber_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "タグ一覧", tags_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
        <% else %>
          <li><%= link_to "About", about_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "Youtuber一覧", youtubers_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "ログイン", new_user_session_path,class:"btn btn-light btn-outline-secondary btn-margin" %></li>
          <li><%= link_to "タグ一覧", tags_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
        <% end %>
          <li><%= link_to "検索🔍", search_youtubers_path, class:"btn btn-light btn-outline-secondary btn-margin" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForYoutubers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <header class="border-bottom d-flex flex-column">
      <%= render "layouts/header" %>
    </header>
    <div class="Notification">
     <% flash.each do |key, value| %>
       <%= content_tag :div, value, class: key %>
     <% end %>
    </div>

    <%= yield %>
    <footer class="border-top">
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>